make: client.c server.c
	gcc -std=c99 -std=gnu99 -pthread -o client client.c
	gcc -std=c99 -std=gnu99 -pthread -o server server.c

debug: cliento. server
	gcc -std=c99 -std=gnu99 -pthread -o client client.c
	gcc -std=c99 -std=gnu99 -pthread -o server server.c

clean:
	rm client server
